# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sietsma Family Website
subtitle: For Sietsmas all over the workd
email: korny@sietsma.com
url: https://sietsma.com
description: >- # this means to ignore newlines until the next outdent
  The Sietsma family website, for Sietsmas all over the world.
repository: "kornysietsma/sietsma-site"
minimal_mistakes_skin: air
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Note permalink only works for posts not pages
permalink: /:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/London # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  # - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      # permalink doesn't work here, needs to be in every page
      # permalink: /:basename/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

